Hyundai-Kia-Connect/kia_uvo

custom_components/kia_uvo/Vehicle.py, custom_components/kia_uvo/__init__.py, custom_components/kia_uvo/const.py
Time data seems to come in Western European time -
This was previously causing the last update time to show as "In 30 minutes" for example, for me in the UK, as the time often looked like it was in the future.
This adds Tz data to the last update time, so the system can work out local time and display this
=> use Tz data so last update time shows correctly

custom_components/kia_uvo/sensor.py
The range data coming from Kia is a bit all over the place :-) sometimes I get the distance km, and then after I do a force refresh in Home Assistant I get the distance in miles (which is what I have set on the Kia UVO iOS app settings). 
But the units displayed in the integrations weren't updating as it was working them out in the init code, rather than on each update. So in the examples below, the range is first 277km, and then after the force update 172 miles, but it still says km.
Before force update:
After force update:
=> Move where dynamic unit is enumerated

custom_components/kia_uvo/manifest.json
I've got a few other integrations that use the [Hassfest](https://developers.home-assistant.io/blog/2020/04/16/hassfest/) github action to validate the integration. These all started failing a couple of days ago due to lack of [iot_class](https://developers.home-assistant.io/docs/creating_integration_manifest/#iot-class)  in the manifest. So I'm adding this here to, as I guess it is going to become a requirement
=> Add iot_class to manifest

custom_components/kia_uvo/sensor.py
Needed to make an extra little change so that the dynamic units of measurement sensors had their units updated each time rather than only the first loop around.
=> Make sure dynamic UoM sensors units are not only checked the first time

custom_components/kia_uvo/sensor.py
fix based on stack trace of, added debug logging for absent sensors as I'm hoping this is an easy pr to merge
```
2021-11-09 12:27:33 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up kia_uvo platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 257, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 607, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 715, in add_to_platform_finish …
```
=> fix: odometer value of 19518.4 error

custom_components/kia_uvo/Vehicle.py
because it does have a lowFuelLight and is an EV
happy to switch to better implementation, this seemed the least invasive change
maybe if we compared vehicle data we could see a pattern in the more explicit attributes like driveType or fuelType
for reference
```
'{"status":{"statusCode":0,"errorType":0,"errorCode":0,"errorMessage":"Success with response body"},"payload":{"vehicleInfoList":[{"vinKey":"kkk","vehicleConfig":{"vehicleDetail":{"vehicle":{"vin":"vvv","trim":{"modelYear":"2019","salesModelCode":"V1262","optionGroupCode":"015","modelName":"NIRO EV","factoryCode":"DQ","projectCode":"DEEV","trimName":"EX PREMIUM","driveType":"0","transmissionType":"1","ivrCategory":"6","btSeriesCode":"N"},"telematics":1,"mileage":"12110.8","mileageSyncDate":"20211107085034","exteriorColor":"ALUMINUM …
```
=> fix: Niro 2019 EV being labeled PHEV

custom_components/kia_uvo/KiaUvoApiCA.py
Updated Kia Canada to point to the new Kia Connect URL. kiaconnect.ca
=> fix: Adjusted Kia Canada Login URL

custom_components/kia_uvo/HyundaiBlueLinkAPIUSA.py, custom_components/kia_uvo/Vehicle.py
The location information provided in the cached vehicle status does not
include decimal precision.  In order to fix this, implement the
get_location method in the api for Hyundai USA.
Considering that there is a daily API limit, poll the get_location
method based on whether or not the odometer changed.  It will also keep
track of the last time that the location was retrieved form the server,
and only fetch a new location if the last update was more than an hour
ago.
=> fix: Hyundai USA: support a separate location fetch (Issue #196)

custom_components/kia_uvo/__init__.py
Removed a duplicate vehicle.refresh_token().  This is called in line 195 as refresh_config_entry first refresh's the token.  This is causing duplicate vehicle calls in the USA implementation for Hyundai due to the short token time.
=> fix: Duplicate vehicle.refresh_token() call

custom_components/kia_uvo/__init__.py
Scan times were incorrectly assuming the API's time zone was the same as the users time zone.
=> fix:  Scan times not following time zone

custom_components/kia_uvo/sensor.py
Example that shows the math error:  Starting value is 22 yet it returns 16.
```
CA_TEMP_RANGE = [
16,
16.5,
17,
17.5,
18,
18.5,
19,
19.5,
20,
20.5,
21,
21.5,
22,
22.5,
23,
23.5,
24,
24.5,
25,
25.5,
26,
26.5,
27,
27.5,
28,
28.5,
29,
29.5,
30,
30.5,
31,
31.5,
32,
]  
set_temp = CA_TEMP_RANGE.index(22)
print(set_temp)
set_temp = hex(set_temp).split("x")
set_temp = set_temp[1] + "H"
set_temp = set_temp.zfill(3).upper()
print(set_temp)
value = set_temp.replace("H", "")
value = value.replace("C", "")
value = "0x" + value
value = CA_TEMP_RANGE[int(value, 16)]
print(value)
```
=> fix:  Corrected hex issue impacting 22C Display

custom_components/kia_uvo/KiaUvoEntity.py, custom_components/kia_uvo/sensor.py
This PR adds [long term statistics](https://data.home-assistant.io/docs/statistics/) for the following sensors:
- EV Battery
- EV Range
- Total Range
- Odometer
Other (non-EV) sensors might be interesting as well to add as long term statistics in HA, but I am only able to test EV-sensors.
=> feat: Add long term statistics

custom_components/kia_uvo/__init__.py
This PR fixes the issue when `no_force_scan_hour_start` is smaller than `no_force_scan_hour_finish`.
For example, configuring no force update between 01h00 and 05h00 would result in the forced update _only_ triggering between those hours, in stead of outside the range. 
The `if`-statement now checks whether `no_force_scan_hour_start <= no_force_scan_hour_finish` and applies a slightly different logic.
=> fix: force update scan when start < finish

hacs.json
Sets the minimum home assistant version required for this to run as we have seen two issues reported due to this.
=> fix: Added HACS minimum HA Version

custom_components/kia_uvo/coordinator.py
The last step of a force refresh call in the API is to refresh from the cache as the cache is now current.  Calling it before we force an update just increases API calls.
=> fix: Reduced API calls.

custom_components/kia_uvo/sensor.py
Super minor fix for the unit_of_measurement for last_update. Should not be the string `"None"` but simply state `None` (just like geocodedLocation)
It fixes my InfluxDB measurements 👍
=> fix: last_updated unit of measurement

.github/pre-commit-config.yaml
current workflows are failing because of outdated black
=> chore: upgrade black to latest version

custom_components/kia_uvo/__init__.py, custom_components/kia_uvo/climate.py
Adding climate control to the HYU/KIA integration.
This is a total Draft. My Ioniq Electric is only arriving in a few weeks and i never touched python for anything bigger than a 10-liner.
However, i would like my car to be fully controllable so i want to devote time into the HA integration. Since you guys already started the process, i would like to append to your work :)
Please let me know your thoughts and code criticisms since you also build the actual HYU/KIA Connect python lib.
**As discussed in https://github.com/fuatakgun/core/pull/7, i understand basing this on top of `generic_thermostat` might make more sense. However before i can approach that:**
- i need a car, hopefully 1-2 weeks :laughing: 
- generic_termostat wants the toggles for heater/ac be separate switches. It also …
=> feat: add climate control as climate platform

custom_components/kia_uvo/__init__.py, custom_components/kia_uvo/manifest.json, custom_components/kia_uvo/number.py
NOTE: this depends on
- https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/pull/53
- https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/pull/54
After the lib provides the features to get/set EV charging limits, this provides them as number integration for EU:
=> feat(EU): set charging limits as number_input

custom_components/kia_uvo/KiaUvoApiEU.py, custom_components/kia_uvo/sensor.py
This PR adds two sensors for EV's:
- Average Energy Consumption (30 day moving average)
- Total Energy Consumption
The average shows in watt per kilometer (mile) the average usage of the past 30 days.
The total consumption shows in kwh the total energy consumption since the vehicle was connected to Bluelink. This sensor can be used in conjuction with the Home Assistant Energy dashboard as an individual device, allowing one to see daily, weekly, monthly statistics. The sensor also includes as attributes other information such as recuperation energy and climate usage (in watt).
This code has been running for more than a month now in my setup.
There are three considerations:
1. Only tested in EU
2. Only tested with EV. Not sure if the same / comparable api is available for fuel cars
3. It …
=> feat(EU): EV sensors for average consumption & energy used

custom_components/kia_uvo/sensor.py
https://developers.home-assistant.io/blog/2022/09/28/deprecate-conversion-utilities/
Resolves #372
=> fix: Removed deprecated home assistant class

custom_components/kia_uvo/sensor.py
SSIA
As per discussion with @cdnninja
=> fix: Don't use device_class battery for 12V battery in v2.0

custom_components/kia_uvo/services.yaml
Require heating setting for start_climate as all regions do require it.  Resolves https://github.com/fuatakgun/kia_uvo/issues/447.
=> fix: Require heating for start_climate

custom_components/kia_uvo/services.py, custom_components/kia_uvo/services.yaml
First step of no longer needing a device selected for service calls.  This removes the requirement for Update and Force Update.
#533
=> fix:  No Longer Require ID for Update

custom_components/kia_uvo/services.py, custom_components/kia_uvo/services.yaml
I don't think ideal checking the API for vehicle count instead of home assistant but seemed easier.  #533
=> fix: Vehicle no longer required for all service calls

custom_components/kia_uvo/number.py
This update will improve the usability of the numbers:
=> feat: set SOC levels as number instead of slider

custom_components/kia_uvo/sensor.py
Since the odometer  is a value that is only destined to increase, total_increasing should be the most suitable option.
Moreover this should resolve some erratical statistics when the sensor becomes unavailable (statistics card and graphs, daily mileage when feeding an utilty meter etc)
=> fix: Change odometer state_class to total_increasing

custom_components/kia_uvo/number.py
This makes the change of charge limit much more convenient. Previously, with BOX, it's impossible to change the limit. If you delete one digit, it goes to 50; if you add a digit, it goes to 100. Now the life is made easier.
=> feat: Change the Charge Limit from BOX to SLIDER

custom_components/kia_uvo/manifest.json
note: don't merge until the version is manually bumped in `hyundai_kia_connect_api`.
this pr updates the dependency to get the latest Australia fixes.
=> fix: bump dependent hyundai_kia_connect_api version to 3.8.4

custom_components/kia_uvo/translations/nl.json
=> feat: Dutch Language Support

custom_components/kia_uvo/binary_sensor.py
Hello,
this commit adds a new binary_sensor for the status of the brake fluid warning field.
It is almost identical to the already existing washer fluid warning sensor.
Best regards
=> feat: Addition of a binary sensor for brake fluid warning.

custom_components/kia_uvo/sensor.py
Hello,
this PR adds a sensor containing the data stored in the daily_stats field of the Vehicle objects since currently these data are not accessible in Home Assistant. The data are contained in the attributes of the sensor - one attribute per day which is identified via a datetime.date object. The values of each day are stored in a dictionay with the same keys used by the hyundai_kia_connect_api. I think having such a sensor is very useful to further process the data by e.g. templates.
Best regards
=> feat: Addition of sensor for the daily driving stats data.

custom_components/kia_uvo/sensor.py
Hello,
this PR adds a sensor for the "total_power_regenerated" field which is already present in the API but not yet included in the Home Assistant integration. Following to the naming of the sensor for the field "total_power_consumed" which is already existing, the sensor should be named "Monthly Energy Regeneration", but as I stated in issue #751 I think there are multiple indications that the naming "Monthly" is wrong and should actually be "Total" like in the field name, so I named the sensor "Total Energy Regeneration" - Please correct me if I'm wrong.
Best regards
=> feat: Addition of sensor for Total Power Regenerated

custom_components/kia_uvo/sensor.py
Hello,
as discussed in issue #755 this PR changes the datatype of the attribute keys of the daily driving stats sensor to string using the default date-format of Python "%Y-%m-%d". I hard-coded the format to avoid problems if for any reason the default date to string conversion of Python should change in the future. The change is neccessary to overcome the limitation of the InfluxDB integration which at the moment allows only for string-type attribute keys.
Best regards.
=> fix: Workaround to overcome limiations in InfluxDB

custom_components/kia_uvo/sensor.py
We want to have state_class defined to have it stored in long term statistics.
More information:
https://developers.home-assistant.io/blog/2021/05/25/sensor_attributes/
=> feat: Add Measurement state_class to EV Battery Level

custom_components/kia_uvo/coordinator.py, custom_components/kia_uvo/manifest.json
Calls to lock, unlock, start_climate, stop_climate, start_charge, stop_charge and set_charge_limits now update the state of the vehicle when complete.
TL/DR: ``await async_request_refresh()`` has been replaced by ``don't await, async try to wait until action is done and finally async_refresh()``. The try block should ensure that this feature is completely neutral or additive.
This was done by adding a new ``async_await_action_and_refresh`` function to the coordinator. It adds ``check_action_status`` that awaits for success or error before calling ``async_refresh``. This function is called using ``async_create_task`` so that the action can finish without having to wait for a response that can take about 30 to 60 seconds. Since the function now waits for the action to complete before …
=> feat: calls update state on completion

custom_components/kia_uvo/sensor.py, custom_components/kia_uvo/services.py
Sorry, had to rework the `value_fn` since that was not available on the SensorEntityDescription.
Furthermore I forgot to add it to the services setup... my bad.
=> fix: charging current initialisation

custom_components/kia_uvo/coordinator.py, custom_components/kia_uvo/manifest.json, custom_components/kia_uvo/services.py, custom_components/kia_uvo/services.yaml, custom_components/kia_uvo/translations/en.json
Should fix https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/928
=> feat(EU): add schedule charging service

custom_components/kia_uvo/sensor.py
Adds a sensor for "Todays Daily Driving Stats" which allows for a fixed sensor to access daily stats instead of the moving target of the date labeled attribute in the main daily driving stats sensor.
This makes it easier to pull the current days stats and have it reset at midnight as it will switch to default 0 values. instead of using template workarounds such as those discussed in #870 or other helper implementations people may be using.
the entity gets added along with the normal Daily Driving Stats so it only exists if that does and draws data using the same method.
NB: 1st PR on a HA integration, please be kind.
=> feat: Add Sensor for todays daily stats

custom_components/kia_uvo/services.py, custom_components/kia_uvo/services.yaml, custom_components/kia_uvo/translations/en.json
to allow for Low/High setting. Related PR for hyundai_kia_connect_api/feature/steering_wheel_step
=> feat: Adds steering wheel heat as its own selector
