Hyundai-Kia-Connect/kia_uvo

- custom_components/kia_uvo/binary_sensor.py
Adds binary sensors for:
* battery charging
* car plugged in
* low fuel
> Adds charging, plugged in, and low fuel sensors

- custom_components/kia_uvo/sensor.py
Pure EV doesn't have fuel, so split that out for PHEV only.
> no fuel in pure ev

- custom_components/kia_uvo/sensor.py
> Output datetime in isoformat

- custom_components/kia_uvo/sensor.py
Get geocodedLocation from vehicleLocation instead of vehicleStatus.
> Get geocodedLocation from vehicleLocation

- custom_components/kia_uvo/KiaUvoApi.py
Change zoom to include house_number for geocoded location from osm.
> Change zoom to include house_number

- custom_components/kia_uvo/sensor.py
Changed order of EV battery to try make the EV battery take priority in the dashboard.  An attempt to resolve #54
> Changed order of EV battery addition

- custom_components/kia_uvo/KiaUvoApiCA.py
Corrected two errors in the new code.   Currently hitting API call max so can't test further.   At some point we need to catch that error so I don't have to restart home assistant to resolve.   I have also noticed you can still use the website.  This implies the token is maxed not the car.  A relogin may allow more API calls.
> Corrected odometer response and Vehicle call

- custom_components/kia_uvo/KiaUvoApiCA.py
- custom_components/kia_uvo/binary_sensor.py
- custom_components/kia_uvo/sensor.py
Added remote start
Filters binary entities to only ones available on that vehicle.
Remote start is not fully tested.
> Added remote start to CAD and Entity Filters

- custom_components/kia_uvo/sensor.py
Corrected time zone and exempted it from filters.   Please validate this doesn't break europe, I am assuming it is okay.
> Bug fix for updated time filter

- custom_components/kia_uvo/KiaUvoApiCA.py
- custom_components/kia_uvo/sensor.py
Added new features including location, last service, next service, and status verification.  Error handling also started for location.
> CA Feature Additions

- custom_components/kia_uvo/KiaUvoApiCA.py
- custom_components/kia_uvo/KiaUvoApiEU.py
- custom_components/kia_uvo/KiaUvoApiImpl.py
- custom_components/kia_uvo/Vehicle.py
- custom_components/kia_uvo/__init__.py
- custom_components/kia_uvo/services.yaml
Fixes #73.  Please test this on other vehicle types and EU.
> Updated EV detection for CA

- .github/workflows/lintPR.yml
Added a github action to start to encourage me to use Semantic titles on PRs.  This will help us if we move to automated releases.  Example of what this and HACs will look like: https://github.com/cdnninja/kia_uvo/pull/8
> feat: Added PR Lint Checking

- custom_components/kia_uvo/services.yaml
Corrected services to allow temperature in Fahrenheit in prep for USA support.  Clarified some text.
> fix: Corrected services to allow for other regions

- custom_components/kia_uvo/HyundaiBlueLinkAPIUSA.py
Depends on https://github.com/fuatakgun/kia_uvo/pull/97
> feat: Lock/Unlock for Hyundai USA

- custom_components/kia_uvo/KiaUvoApiCA.py
- custom_components/kia_uvo/Vehicle.py
- custom_components/kia_uvo/__init__.py
Corrected EV remote start/stop for CA and added charge start stop.
> feat: Added EV to CA

- custom_components/kia_uvo/KiaUvoAPIUSA.py
I added the fix for stale sessions and catch invalid responses from the server for logging.  I put this as a second PR but with  https://github.com/fuatakgun/kia_uvo/pull/122 included as it builds on those functions and drys them up, if you merge this I'll close 122 or if 122 is merged it will reduce the diff on this PR.
> feat: USA Kia reauth, lock, unlock, start and logging responses

- custom_components/kia_uvo/KiaUvoAPIUSA.py
so force refresh shows updated results, followed sleep timing based on timing used in android mobile app
> feat: usa kia track actions until async server action is completed

- .github/workflows/validate.yml
- hacs.json
Added validation for HACS.
Create hacs.json
> feat: Added HACS Validation

- custom_components/kia_uvo/Token.py
- custom_components/kia_uvo/Vehicle.py
Aligned to Python 3.8.  Tested in my HA setup.
> fix: Aligned to PyUpgrade

- custom_components/kia_uvo/binary_sensor.py
> feat: Added Heat Seater State

- .github/workflows/release.yml
- custom_components/kia_uvo/KiaUvoApiEU.py
Added version release with a Wed and Sunday build.  Manual builds can be done via the actions menu. 
Closes #155
> feat: Version and release github action

- .github/workflows/lint.yaml
A token needs to be created and stored as  secrets.PAT before this can be merged.   Closes #143.
> feat: Lint Black Auto Correction for Remote Fork

- custom_components/kia_uvo/KiaUvoApiCA.py
> fix: Canada fix for cars that have never been serviced

- custom_components/kia_uvo/manifest.json
Resolved an error about bs4 missing for EU setup. Resolves #165
> fix: Resolved Error in EU Setup

- .github/workflows/release.yml
> fix: Corrected Version Numbers in HA

- custom_components/kia_uvo/HyundaiBlueLinkAPIUSA.py
> fix:  Corrected Hyundai USA location data and Tires

- custom_components/kia_uvo/HyundaiBlueLinkAPIUSA.py
- custom_components/kia_uvo/KiaUvoAPIUSA.py
- custom_components/kia_uvo/KiaUvoApiCA.py
- custom_components/kia_uvo/KiaUvoApiEU.py
- custom_components/kia_uvo/KiaUvoApiImpl.py
- custom_components/kia_uvo/Vehicle.py
- custom_components/kia_uvo/__init__.py
- custom_components/kia_uvo/config_flow.py
- custom_components/kia_uvo/utils.py
> chore: replace blocking IO with async http library for USA implementation

- custom_components/kia_uvo/KiaUvoAPIUSA.py
> fix: USA KIA Corrected Evstatus error

- custom_components/kia_uvo/HyundaiBlueLinkAPIUSA.py
> fix(Hyundai USA): corrected odometer readings

- custom_components/kia_uvo/KiaUvoAPIUSA.py
Check for tire pressure before mapping it.
> fix(USA KIA): Check for tire pressure

- custom_components/kia_uvo/Vehicle.py
> fix(Canada):  Corrects region lookup impacting EV start

- custom_components/kia_uvo/HyundaiBlueLinkAPIUSA.py
Leaving in draft as this only does login right now.
> fix(USA Hyundai): Allow weaker ciphers since Hyundai uses these

- custom_components/kia_uvo/KiaUvoAPIUSA.py
Corrected data order for multiple sensors.  Will use this commit for #227.   Odometer will be looked at next.
> fix(USA KIA): Resolved multiple sensors not showing

- custom_components/kia_uvo/__init__.py
Leaving in draft while I watch how my system responds to this over the next few hours.
> fix:  Corrected sensor unavailable errors

- custom_components/kia_uvo/sensor.py
> fix:  Corrected fuel level device class

- custom_components/kia_uvo/KiaUvoAPIUSA.py
> fix(USA Kia):  Corrected distance to empty for EV

- custom_components/kia_uvo/__init__.py
- custom_components/kia_uvo/device_tracker.py
Still requires a bit of API work for this value to exist in the car.    Will post for review purposes. Won't merge until I have the API working on this as well.
> feat: Location Entity

- custom_components/kia_uvo/KiaUvoAPIUSA.py
Update API request to download maintenance information and added it to vehicle_data to be returned as a sensor entity (sensor is already defined in sensor.py, variable just needed to be defined within KiaUvoAPIUSA file).
> feat(US Kia): Added miles until next service information

- custom_components/kia_uvo/manifest.json
- custom_components/kia_uvo/translations/en.json
> fix: do not translate title

- custom_components/kia_uvo/KiaUvoApiCA.py
Resolve #307  Requires testing.
> feat(CA): Set Charging Limits

- custom_components/kia_uvo/KiaUvoApiEU.py
> fix(EU):  Changed logging for EV features

- .github/workflows/release.yml
Switching to a supported release action as this was causing warnings to NPM version being end of life.
> chore: Updated Release action

- custom_components/kia_uvo/Vehicle.py
- custom_components/kia_uvo/sensor.py
Fix right path to targetSOC, only ac_limit or dc_limit stay None in def set_charge_limits, and why that is, eludes me.
> fix: targetSOC, but not quite

- custom_components/kia_uvo/Vehicle.py
- custom_components/kia_uvo/sensor.py
The start of logic to not use defaults to set a charge limit.  Goal will be to get current limits rather than set defaults.
> fix: Charge limit logic change

- custom_components/kia_uvo/services.py
Corrected syntax for remote start.
> fix: Service remote start call get data.

- custom_components/kia_uvo/coordinator.py
> fix:  Force update data

- custom_components/kia_uvo/sensor.py
SSIA.
As per discussion with @cdnninja 
Fixes #240
> fix: Don't use device_class battery for 12V battery (master)

- custom_components/kia_uvo/coordinator.py
- custom_components/kia_uvo/services.py
Corrected ev charge limits service.
> fix:  Set Charge Limits

- custom_components/kia_uvo/number.py
> fix: Remove Deprecated Number

- custom_components/kia_uvo/coordinator.py
> fix: EV Charge Limits

- custom_components/kia_uvo/number.py
This is untested as I don't have an EV.
> fix: Number alignment to coordinator model

- custom_components/kia_uvo/config_flow.py
- custom_components/kia_uvo/const.py
- custom_components/kia_uvo/coordinator.py
- custom_components/kia_uvo/manifest.json
- custom_components/kia_uvo/sensor.py
- custom_components/kia_uvo/translations/en.json
Not ready to merge yet as the API needs update to support this.  As such not tested yet.
> feat:  Return of Geolocation

- custom_components/kia_uvo/binary_sensor.py
> fix: Device Class for Tires and Doors

- custom_components/kia_uvo/coordinator.py
- custom_components/kia_uvo/number.py
- custom_components/kia_uvo/services.py
Requires https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/pull/150/files
> fix: Number entity for SOC

- custom_components/kia_uvo/sensor.py
Requires: https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/pull/92
Resolves #403
> feat: Added Energy Consumption Sensors

- custom_components/kia_uvo/coordinator.py
- custom_components/kia_uvo/manifest.json
- custom_components/kia_uvo/services.py
- custom_components/kia_uvo/services.yaml
https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/243
> feat(EU): Charge Port Control

- custom_components/kia_uvo/sensor.py
Allows for setting distance preference.
> fix: Distance Setting

- custom_components/kia_uvo/sensor.py
Average Energy Consumption unit of measure
> fix: Average Energy Consumption Unit of Measure

- custom_components/kia_uvo/__init__.py
Resolves https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/489
> fix: Services Unavailable

- custom_components/kia_uvo/manifest.json
- custom_components/kia_uvo/sensor.py
#489 this should add the soc range back.
> fix(EU): Target SOC Range

- custom_components/kia_uvo/coordinator.py
fix start charge service currently sending stop charge to car
> fix: start charge service

- custom_components/kia_uvo/translations/de.json
> feat: German Config Translation

- custom_components/kia_uvo/coordinator.py
Supports the API using the system language
> feat(EU): Support for language

- .github/ISSUE_TEMPLATE/bug_report.md
> docs: Fix link to readme.md in issue_template

- custom_components/kia_uvo/strings.json
- custom_components/kia_uvo/translations/en.json
re-auth support when password incorrect.
> feat: Re-auth Support

- custom_components/kia_uvo/__init__.py
Fixes #581 
Works fine locally.
> fix: deprecated method

- custom_components/kia_uvo/lock.py
https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/584#issuecomment-1414478464
> fix:  Lock Errors

- custom_components/kia_uvo/translations/hu.json
Hungarian translation file added
> feat: Hungarian Translation

- custom_components/kia_uvo/manifest.json
> fix(EU): stamp generation

- custom_components/kia_uvo/translations/en.json
Should clear up CI checks for HACS.
> fix: Translation for services in English

- custom_components/kia_uvo/translations/en.json
> fix: English Spelling Mistake

- custom_components/kia_uvo/translations/de.json
> feat: Improved German Translation

- README.md
- custom_components/kia_uvo/manifest.json
> feat(USA): Genesis Support

- custom_components/kia_uvo/translations/fr.json
Adding the French translation file for the plugin
> feat: french translation

- custom_components/kia_uvo/manifest.json
closes https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/775
> feat(USA): Kia seat support

- custom_components/kia_uvo/climate.py
- custom_components/kia_uvo/device_tracker.py
- custom_components/kia_uvo/sensor.py
Went through the codebase to fix the deprecated constant warning from HA 2024.1.0b2.
Had these in my log:
```py
2023-12-31 13:12:33.939 WARNING (MainThread) [homeassistant.const] TIME_MINUTES was used from kia_uvo, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTime.MINUTES instead, please create a bug report at https://github.com/fuatakgun/kia_uvo/issues
2023-12-31 13:12:33.946 WARNING (MainThread) [homeassistant.const] TIME_DAYS was used from kia_uvo, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTime.DAYS instead, please create a bug report at https://github.com/fuatakgun/kia_uvo/issues
2023-12-31 13:12:33.953 WARNING (MainThread) [homeassistant.const] ENERGY_WATT_HOUR was used from kia_uvo, this is a deprecated …
```
> fix: change deprecated constants for HA 2024.1

- README.md
- custom_components/kia_uvo/manifest.json
- custom_components/kia_uvo/sensor.py
In the newest pull request for the hyundai_kia_connect_api https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/pull/489 there are three additional attributes exposed:
- SoH state of health in percentage
- Capacity as int value
- Remain (Capacity) as int value
> feat(EU): Additional battery sensors

- custom_components/kia_uvo/manifest.json
Corrected documentation and issue tracker links
> fix: Update manifest.json

- custom_components/kia_uvo/sensor.py
> feat: Add V2L discharge limit

- custom_components/kia_uvo/sensor.py
Same as https://github.com/Hyundai-Kia-Connect/kia_uvo/pull/831, also make battery remaining and capacity a measurement
> feat: update sensor.py

- custom_components/kia_uvo/manifest.json
- custom_components/kia_uvo/sensor.py
depends on https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/pull/684
> feat: Add EV Charging Power

- custom_components/kia_uvo/manifest.json
(Hyundai-Kia-Connect/hyundai_kia_connect_api#702)
> fix: climate control functionality for EV vehicles in Canada (Hyundai-Kia-Connect/hyundai_kia_connect_api#702)

- custom_components/kia_uvo/translations/da.json
Addition of Danish language package :-)
> feat: Addition of Danish language package :-)

- custom_components/kia_uvo/translations/sv.json
> feat: Add swedish translation

- custom_components/kia_uvo/config_flow.py
Make it consistent with current Home Assistant API & practices.
Fixes https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/1029
I didn't bump the version, probably you'll do you own release process.
Tested to work fine:
> fix: non-working config flow
